#! /bin/sh

if [ $# -ne 3 ]; then
    echo "USAGE: $0 <remote image> <local image file> <final name>"
    echo "ex: $0 quay.io/coreos/hyperkube:v1.5.1_coreos.0 hyperkube-v1.5.1_coreos.0.aci example.com/hyperkube"
    exit 1
fi

set -ex

remote_image="$1"
local_image="$2"
final_name="$3"

local_dir="${local_image}.dir"

if ! [ -e "$local_dir" ]; then
    rkt fetch --trust-keys-from-https "$remote_image"
    rkt image render "$remote_image" "$local_dir"
fi

actool build "$local_dir" "$local_image"
rm -fr "$local_dir"

actool patch-manifest -name "$final_name" -replace "$local_image"
chmod a+r "$local_image"
